# Settings specified under default heading apply to all environments
default:

    # Default context 
    context:

        # Default data source
        data_source:
            _class: cl.runtime.LocalCache   # Data source class name
            data_source_id: Default         # Unique identifier

        dataset: Common

    data_source_settings:

        # Deletion of temporary databases (e.g. those used for caching or testing) via the API
        # is allowed only if 'temp_id_pattern' is specified and matches data_source_id
        temp_id_pattern: Temp.*

    # REST API settings do not affect the UI
    api_settings:

        # Optional package aliases for the REST API, and DB in 'pattern: alias' format.
        # Use this feature to organize types by package in large projects and to
        # resolve conflicts when classes in different modules share the same class name.
        # - When module does not match the glob pattern, ClassName is used without prefix
        # - When module matches the glob pattern, alias.ClassName is used.
        # This setting has no effect where full module is required, e.g., for the _class field.
        package_aliases:
            cl.runtime: rt
            stubs.cl.runtime: rt

    # UI settings do not affect the REST API
    ui_settings:

        # Optional humanized package label in 'pattern: label' format for the UI only.
        # Use this feature to organize types by package in large projects and to
        # resolve conflicts when classes in different modules share the same class name.
        # - For modules that do not match the glob pattern, no package name is used
        # - This UI setting does not affect the REST API
        package_labels:
            cl.runtime: Runtime
            stubs.cl.runtime: Runtime Stubs

        # Replace humanized class name by the specified label for the UI only
        # - When not specified, the name is humanized according to ClassName -> Class Name
        # - This UI setting does not affect the REST API
        type_labels:
            SampleClass: Sample Class Label

        # Replace humanized field name by the specified label for the UI only
        # - When not specified, the name is humanized according to field_name -> Field Name
        # - This UI setting does not affect the REST API
        field_labels:
            sample_field: Sample Field Label

        # Replace humanized method name by the specified label for the UI only
        # - When not specified, the name is humanized according to method_name -> Method Name
        # - This UI setting does not affect the REST API
        method_labels:
           sample_method: Sample Method Label

        # Replace humanized method name by the specified enum item (member) for the UI only
        # - When not specified, the name is humanized according to ITEM_NAME -> Item Name
        # - This UI setting does not affect the REST API
        item_labels:
            SAMPLE_ITEM: Sample Item Label
