# Default environment is used if no environment is specified
[default]

# Refer to the ContextSettings class for documentation
runtime_context_packages = ["cl.runtime", "stubs.cl.runtime"]  # TODO: Prefix or glob pattern
runtime_context_data_source_class = "cl.runtime.storage.sql.sqlite_data_source.SqliteDataSource"  # TODO: Deprecated
runtime_context_data_source = "Runtime Default"

# Refer to the ApiSettings class for documentation
runtime_api_host_name = "localhost"
runtime_api_host_ip = "127.0.0.1"
runtime_api_port = 7008

# Refer to the PreloadSettings class for documentation
runtime_preload_dirs = ["preload/cl", "preload/stubs"]
