# Default environment
default:

  # Documented in LogSettings class
  runtime_log_level: info
  runtime_log_filename_prefix: main

  # Documented in ContextSettings class
  runtime_context_packages:
      - cl.runtime
      - stubs.cl.runtime
  runtime_context_db_class: cl.runtime.db.sql.sqlite_db.SqliteDb

  runtime_context_experiment: SampleExperiment
  runtime_context_trial: SampleTrial
  runtime_context_mini_llm: gpt-4o-mini
  runtime_context_full_llm: gpt-4o

  # Documented in ApiSettings class
  #   - Default CORSMiddleware settings are only applied on localhost
  #   - If this group of settings is omitted, the app will run on localhost:7008
  runtime_api_hostname: localhost
  runtime_api_port: 7008

  # CORSMiddleware settings in ApiSettings class, uncomment and modify if not running in localhost
  # runtime_api_allow_origins:
  #   - 127.0.0.1
  # runtime_api_allow_origin_regex: null
  # runtime_api_allow_credentials: True
  # runtime_api_allow_methods:
  #   - "*"
  # runtime_api_allow_headers:
  #   - "*"
  # runtime_api_expose_headers: null
  # runtime_api_max_age: null

  # Documented in PreloadSettings class
  runtime_preload_dirs:
      - preloads/cl
      - preloads/stubs

# Test environment
test:

  # Documented in LogSettings class
  runtime_log_filename_prefix: tests

