# Default environment
default:

  # Documented in LogSettings class
  runtime_log_level: info
  runtime_log_filename_prefix: main

  # Documented in ContextSettings class
  runtime_context_packages:
    - cl.runtime
    - cl.convince
    - cl.tradeentry
    - stubs.cl.runtime
    - stubs.cl.convince
    - stubs.cl.tradeentry
  runtime_context_db_class: cl.runtime.db.sql.sqlite_db.SqliteDb

  # Documented in ApiSettings class
  runtime_api_hostname: localhost
  runtime_api_port: 7008

  # Documented in PreloadSettings class
  runtime_preload_dirs:
    - preloads/cl
    - preloads/stubs

  # Documented in TradeEntrySettings class
  tradeentry_mini_llm: gpt-4o-mini
  tradeentry_full_llm: gpt-4o

# Test environment
test:

  # Documented in LogSettings class
  runtime_log_filename_prefix: tests
